name: cd

on:
  push:
    branches: [main]

jobs:
  Deployment:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Go Tool Chain
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Run The App
        run: ./scripts/buildprod.sh

